const { chromium, launchOptions } = require('./helpers');
const url = process.argv[2], S = process.argv[3];
(async () => {
  const b = await chromium.launch(launchOptions);
  const c = await b.newContext({ viewport: { width: 1280, height: 860 }, colorScheme: 'dark' });
  await c.addInitScript(() => { if (!localStorage.getItem('enfoque:v1')) localStorage.setItem('enfoque:v1', JSON.stringify({ tasks: [{ id: 't', title: 'Tarea de ejemplo', priority: 3, due: null, done: false, createdAt: 1, tags: [] }], habits: [], settings: { notesWelcome: true }, notes: [{ id: 'a', path: 'Ejemplo', body: '# Ejemplo\nTexto de una nota con **negrita** y una lista:\n- uno\n- dos', createdAt: 1, updatedAt: 1 }], updatedAt: 1 })); });
  const p = await c.newPage(); const errs = []; p.on('pageerror', e => errs.push(e.message)); p.on('console', m => m.type() === 'error' && errs.push(m.text()));
  await p.goto(url); await p.waitForFunction(() => document.documentElement.dataset.ready);
  await p.click('#open-settings'); await p.waitForTimeout(200);
  await p.screenshot({ path: S + '/look-settings-dark.png' });
  const bg = () => p.evaluate(() => getComputedStyle(document.body).backgroundColor);
  console.log('system(dark OS):', await bg());
  await p.click('.ap-theme:has-text("Sepia")'); console.log('sepia under dark OS:', await bg(), await p.evaluate(() => document.documentElement.dataset.theme));
  await p.click('.ap-theme:has-text("Claro")'); console.log('light:', await bg());
  await p.click('.ap-theme:has-text("Nórdico")'); console.log('nord:', await bg());
  await p.selectOption('.ap-row:has-text("Fuente de las notas") select', 'lora');
  console.log('note font var:', await p.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--font-note')), '| link added:', await p.evaluate(() => [...document.querySelectorAll('link[href*="fonts.googleapis"]')].map(l => l.href.split('family=')[1])));
  await p.fill('.ap-row:has-text("Tamaño general") input', '110'); await p.dispatchEvent('.ap-row:has-text("Tamaño general") input', 'change');
  console.log('html font-size:', await p.evaluate(() => getComputedStyle(document.documentElement).fontSize));
  await p.click('.ap-row:has-text("Esquinas") .seg:has-text("Rectas")'); console.log('radius:', await p.evaluate(() => getComputedStyle(document.querySelector('.card')).borderTopLeftRadius));
  await p.click('.ap-row:has-text("Densidad") .seg:has-text("Compacta")'); console.log('density:', await p.evaluate(() => document.documentElement.dataset.density));
  await p.evaluate(() => { const i = document.querySelector('.ap-custom input[type=color]'); i.value = '#e11d48'; i.dispatchEvent(new Event('change')); });
  console.log('custom accent:', await p.evaluate(() => getComputedStyle(document.querySelector('.segmented .seg.active')).backgroundColor));
  await p.screenshot({ path: S + '/look-nord.png' });
  await p.click('.ap-presets .chip:has-text("Papel")'); await p.waitForTimeout(200);
  console.log('preset papel:', JSON.stringify(await p.evaluate(() => [state.settings.look.theme, state.settings.look.noteFont, state.settings.accent])));
  await p.evaluate(() => openNoteByLink('Ejemplo')); await p.waitForTimeout(300);
  console.log('note font in reading:', await p.evaluate(() => getComputedStyle(document.getElementById('note-reading')).fontFamily.slice(0, 20)), '| width:', await p.evaluate(() => getComputedStyle(document.querySelector('.note-inner')).maxWidth));
  await p.screenshot({ path: S + '/look-paper-note.png' });
  await p.reload(); await p.waitForFunction(() => document.documentElement.dataset.ready);
  console.log('persisted:', await p.evaluate(() => document.documentElement.dataset.theme), await bg());
  await p.click('#open-settings');
  console.log('ribbon names on:', await p.evaluate(() => [document.documentElement.dataset.riblabels, getComputedStyle(document.querySelector('.rib-label')).display]));
  await p.click('.ap-row:has-text("Barra de la izquierda") .seg:has-text("Solo iconos")');
  console.log('ribbon names off:', await p.evaluate(() => [document.documentElement.dataset.riblabels, Math.round(document.querySelector('.ribbon').getBoundingClientRect().width)]));
  await p.click('.ap-reset button'); console.log('reset:', await p.evaluate(() => document.documentElement.dataset.theme || 'system'), await bg());
  console.log('errors:', errs); await b.close();
})();
